HiP-App/HiP-CmsAngularApp

app/app.routes.ts
app/main.ts
app/shared/auth/admin-guard.ts
app/shared/auth/auth-guard.ts
app/shared/auth/supervisor-guard.ts
app/shared/sidenav/sidenav.component.ts

Adds a SupervisorGuard for supervisor only access
Adds a AdminGuard for administrator only access
Use the Guard for /new-topic

HIPCMS-405 limit access for /new-topic

---

app/shared/auth/admin-guard.ts
app/shared/auth/supervisor-guard.ts
app/shared/sidenav/sidenav.component.ts

HIPCMS-405 fixing errors on build

---

app/core/user/user.service.ts
app/topics/shared/topic.service.ts
app/topics/topic-management/add-subtopic/add-subtopic.component.ts
app/topics/topic-management/edit-topic/edit-topic.component.ts
app/topics/topic-management/new-topic/new-topic.component.ts
app/topics/topic-management/shared/save-topic-view.component.html
app/topics/topic-management/topic-input/topic-input.component.css
app/topics/topic-management/topic-input/topic-input.component.html
app/topics/topic-management/topic-input/topic-input.component.ts

Updates the handling of topic creation to the new API.

HIPANGULAR-24 updates the handling of creating and updating topics

---

app/tag-management/shared/tag-input.component.css
app/tag-management/shared/tag-input.component.html
app/tag-management/tag.module.ts

background: angular2-color-picker does not work with angular 2.3.1

HIPANGULAR-35 replaces angular2-color-picker with an html5 one

---

app/admin/edit-user/edit-user.component.ts
app/admin/pipes/filter.pipe.ts
app/admin/roles.model.ts
app/admin/users-list/users-list.component.css
app/admin/users-list/users-list.component.html
app/admin/users-list/users-list.component.ts
i18n/de.json
i18n/en.json

Repair user list filter according to different criteria, add select for filtering according to roles independent of the language, add roles array in roles model

HIPANGULAR-33 Fix broken user list filter

---

README.md

After merging https://github.com/HiP-App/HiP-CmsAngularApp/commit/ab3e9fdb3616dd53b45744535eeefd11647953f5 our README is outdated... this should make the README up to date again.

Updates the README.md regarding creating optimized version

---

package.json

fix(package): update systemjs to version 0.20.0

---

app/shared/taginput/user-tag-input.component.html
app/users/invite-users/invite-users.component.html
package.json

fix(package): update ng2-tag-input to version 0.7.6

---

.gitignore
cleanup_public.sh

Delete all files which are not needed for public environment: `package.json`; directories `_test_output`, `docs`; all files in the directory `node_modules` except the 5 needed js/css files which are really needed

HIPANGULAR-55 Improve cleanup_public.sh

---

app/authentication/login/login.component.e2e-spec.ts

I ran the test 3 times in TFS to make sure.

HIPANGULAR-56 repairs failing test

---

package.json

Closes #238
https://greenkeeper.io/

chore(package): update sass-loader to version 5.0.1

---

app/authentication/shared/css/style.css
app/authentication/signup/signup.component.html
app/authentication/signup/signup.component.ts
i18n/de.json

The error hint for too short passwords (i. e. less than 6 characters) is shown now.

Iss hipangular 75 bug signup form

---

app/core/user/user.model.ts
app/core/user/user.service.ts
app/users/admin/edit-user/edit-user.component.html
app/users/admin/edit-user/edit-user.component.ts
app/users/shared/edit-student-details/edit-student-details.component.html
app/users/shared/edit-student-details/edit-student-details.component.ts
app/users/userprofile/userprofile.component.css
app/users/userprofile/userprofile.component.html
app/users/userprofile/userprofile.component.ts
app/users/users.module.ts
i18n/de.json
i18n/en.json

... include student details into userprofile and edit user; add additional API calls in user service, update user model; use grow-width class in userprofile instead of own css file

HIPCMS-527 Add edit student details component

---

app/app.component.ts
app/core/user/user.service.ts
app/users/admin/pipes/filter.pipe.ts
app/users/admin/pipes/sort.pipe.ts
app/users/admin/users-list/users-list.component.ts
app/users/students/students.component.css
app/users/students/students.component.html
app/users/students/students.component.ts
app/users/users.module.ts
app/users/users.routing.ts
i18n/de.json
i18n/en.json

Added student-list view for supervisor with  additional fields viz. discipline, current degree, current semester and sort - search functionality on these fields.

Iss hipangular 530 view students data

---

app/tag-management/create-tag-dialog/create-tag-dialog.component.html
app/users/admin/edit-user/edit-user.component.html
app/users/admin/edit-user/edit-user.component.ts
app/users/admin/pipes/filter.pipe.ts
app/users/admin/users-list/users-list.component.css
app/users/admin/users-list/users-list.component.html
app/users/admin/users-list/users-list.component.ts
app/users/students/students.component.css
app/users/students/students.component.html
app/users/students/students.component.ts
hip-theme.scss
i18n/de.json
i18n/en.json

in create-tag-dialog, user-list, student and edit user component

HIPCMS-533 Replace <select> with Material's <md-select>

---

app/core/user/user.service.ts
app/users/admin/users-list/users-list.component.html
app/users/admin/users-list/users-list.component.ts

Fixing API call for the users-list component.

Iss hipcms 567 code refactoring users list

---

package.json

Closes #303
https://greenkeeper.io/

fix(package): update ng2-tag-input to version 0.9.5

---

app/app.component.css
app/app.component.html
app/app.component.ts

Menu will now be highlighted according to active page

Made menu display current active item

---

app/authentication/login/login.component.html

WHioe on the form Allow user to login by pressing enter

Allow user to login by pressing enter

---

app/mobile-content/media/upload-medium-dialog/upload-medium-dialog.component.ts

Only allow mp3 files

---

app/mobile-content/media/edit-medium-dialog/edit-medium-dialog.component.html
app/mobile-content/media/edit-medium-dialog/edit-medium-dialog.component.ts
app/mobile-content/media/media-gallery/media-gallery.component.ts
i18n/de.json

Download media file, replace existing media file

Iss hipcms 694 replace existing media file

---

app/mobile-content/media/media-gallery/media-gallery.component.css
app/mobile-content/media/media-gallery/media-gallery.component.html

Sorry i did not provide the correct descriptio is for this task 
HIPCMS-714 | Fix a bug on media overview page where the edit button for items with long descriptions disappears
-- | --

Clamped div to show ellipsis and hide overflow

---

app/mobile-content/media/media-gallery/media-gallery.component.css
app/mobile-content/media/media-gallery/media-gallery.component.html

Modified ellipsis to add support for other browsers in media gallery

Iss hipcms 714

---

app/app.component.html

iss-hipcms-709:Fixed menu item click

---

app/app.component.ts

Detect browser language and select german only if browser is german

Detect browser language 

---

app/mobile-content/mobile-content.module.ts
app/mobile-content/routes/routes.component.html
app/mobile-content/routes/shared/pipes/route-filter.pipe.ts

iss-hipcms-712: Fixed route durations as hours and minutes using filter

---

app/mobile-content/exhibits/create-exhibit-dialog/create-exhibit-dialog.component.html
app/mobile-content/exhibits/edit-exhibit/edit-exhibit.component.html
app/mobile-content/exhibits/edit-exhibit/edit-exhibit.component.ts
app/mobile-content/exhibits/exhibits.component.ts
app/mobile-content/exhibits/shared/exhibit.model.ts

This allows users to copy coordinates with a comma as well

Allow latitude and longitude to use commas and change t before commiting data

---

app/app.component.html

Display of the `md-list-item` should depend on the condition in `*ngIf`, not the just the link.

Bugfix: Menu-items not hidden for users without access rights

---

Dockerfile

In the `bundle.min.js` created by `npm run build_prod` the paths for the lazy loaded modules do not work.

No bundle as the paths for the lazy loaded modules don't work

---

app/app.component.css
app/mobile-content/exhibits/create-exhibit-dialog/create-exhibit-dialog.component.css
app/mobile-content/exhibits/create-exhibit-dialog/create-exhibit-dialog.component.html
app/mobile-content/exhibits/create-exhibit-dialog/create-exhibit-dialog.component.ts
app/mobile-content/exhibits/edit-exhibit/edit-exhibit.component.css
app/mobile-content/exhibits/edit-exhibit/edit-exhibit.component.html
app/mobile-content/exhibits/edit-exhibit/edit-exhibit.component.ts
app/mobile-content/mobile-content.module.ts
hip-theme.scss
package.json

Added functionality to search the map for a location in exhibits

Iss hipcms 790

---

app/app.component.ts
app/authentication/auth.service.ts

Someone still has to implement this as a popup or sth. similar, but the core functionality (especially in the backend) is finished.

Handle error codes from auth0

---

app/mobile-content/exhibits/exhibits.component.css
app/mobile-content/exhibits/exhibits.component.html
app/mobile-content/exhibits/exhibits.component.ts

The map displays all exhibits from the system in a map. The title of the exhibit appears after hovering over the map marker.

Add all exhibits map to exhibits view

---

i18n/de.json
i18n/en.json

Fix in Json

---

app/topics/shared/user-tag-input/user-tag-input.component.ts
app/topics/topic-management/new-topic/new-topic.component.ts

Took a lot of time to figure out what the error is but now you can add students and supervisors when creating a topic seems ngx chips deletes changes if the model is updated

Iss hipcms 774

---

app/app.component.html
app/app.component.ts

Fixing problem where topic permissions would not allow users to access the whole menu

---

app/app.component.ts
app/mobile-content/exhibits/create-exhibit-dialog/create-exhibit-dialog.component.ts
app/mobile-content/exhibits/edit-exhibit/edit-exhibit.component.ts
app/mobile-content/exhibits/exhibits.component.ts
app/mobile-content/mobile-content.module.ts
app/mobile-content/routes/routes.component.ts

Added Angular google map configuration to the hip-config.json .
When reviewing the new hip-config.jason needed for it to work is 
EDIT (by @objectliteral): Removed sample hip-config.js.

Iss hipcms 772 Change Map-Input to be configurable

---

app/mobile-content/routes/edit-route/edit-route.component.ts

Automatically calculate the route time and distance acording to the different exhibits and recalculate according to the order

Automatically calculate the route time and distance 

---

app/app.component.ts
app/authentication/auth.service.ts
app/authentication/login/login.component.html
app/authentication/login/login.component.ts

Fixing problem with login screen stick especially on Firefox

Iss hipcms 960

---

app/mobile-content/shared/mobile-content-api.service.ts

previously media service was not working for uploading image and audio. There was a issue with token. I just changed id_token to access_token in mobile-content-api.component.ts file

Upload issue for media
